@localurl = http://localhost:1337


POST {{localurl}}/api/leads
Content-Type: application/json

{
  "data":{
    "name": "lisa",
    "email": "lisa@gmail.com",
    "emailSubject": "hello!",
    "message": "here is a test message"
  }
}

###
GET {{localurl}}/api/projects/?populate=deep,2
Content-Type: application/json
